package com.studysnap.backend.dto;

import java.time.OffsetDateTime;
import java.util.List;

public record NoteResponse(
        String id,
        String title,
        String subject,
        String courseProgram,
        String targetProfileType,
        List<String> tags,
        String content,
        String visibility,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        String copiedFromNoteId,
        String copiedFromUserId,
        String copiedFromTitle,
        Boolean copiedFromPublic,
        OffsetDateTime copiedAt,
        String studyPackId,
        String studyPackStatus,
        String summary,
        List<String> keyConcepts,
        List<QuizItem> quiz,
        GeneratedQuizResponse generatedQuiz,
        String lastUsedTargetLearnerLevel,
        Integer quizCount,
        boolean quickReviewAvailable,
        boolean challengeQuizAvailable,
        boolean adaptivePracticeAvailable,
        boolean difficultySelectionAvailable
) {
    public NoteResponse(
            String id,
            String title,
            String subject,
            String courseProgram,
            String targetProfileType,
            List<String> tags,
            String content,
            String visibility,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt,
            String copiedFromNoteId,
            String copiedFromUserId,
            String copiedFromTitle,
            Boolean copiedFromPublic,
            OffsetDateTime copiedAt,
            String studyPackId,
            String studyPackStatus,
            String summary,
            List<String> keyConcepts,
            List<QuizItem> quiz,
            GeneratedQuizResponse generatedQuiz,
            Integer quizCount,
            boolean quickReviewAvailable,
            boolean challengeQuizAvailable,
            boolean adaptivePracticeAvailable,
            boolean difficultySelectionAvailable
    ) {
        this(
                id,
                title,
                subject,
                courseProgram,
                targetProfileType,
                tags,
                content,
                visibility,
                createdAt,
                updatedAt,
                copiedFromNoteId,
                copiedFromUserId,
                copiedFromTitle,
                copiedFromPublic,
                copiedAt,
                studyPackId,
                studyPackStatus,
                summary,
                keyConcepts,
                quiz,
                generatedQuiz,
                null,
                quizCount,
                quickReviewAvailable,
                challengeQuizAvailable,
                adaptivePracticeAvailable,
                difficultySelectionAvailable
        );
    }
}
