import Link from "next/link";
import { ArrowRight, Download, FileText, Globe } from "lucide-react";

type Section = {
  icon: React.ElementType;
  title: string;
  description: string;
  bullets?: string[];
  cta?: { label: string; href: string };
};

const SECTIONS: Section[] = [
  {
    icon: Download,
    title: "Exporting a quiz session",
    description: "On any Session Review page, use the Export button to download a study PDF. Three export options are available:",
    bullets: [
      "Full Review — all questions, answers, explanations, and score summary",
      "Mistakes Only — incorrect answers with accuracy and weak concepts",
      "Weak Concepts — questions from identified weak areas",
    ],
    cta: { label: "Open Library", href: "/library" },
  },
  {
    icon: FileText,
    title: "Export format",
    description: "Exports are PDF files named with the note title and date — for example, notelib-quiz-biology-2026-04-16.pdf.",
    bullets: [
      "Includes question text, answers, and explanations",
      "Score summary and weak concepts section at the top",
      "Subtle Generated by NoteLib footer — clean for sharing",
    ],
  },
  {
    icon: Globe,
    title: "Sharing notes publicly",
    description: "On the note detail page, use the visibility toggle to set a note to Public. It will appear in the Public Library for other students to view and copy.",
    cta: { label: "Browse Public Library", href: "/public/library" },
  },
];

export function ExportSharingGuide() {
  return (
    <div className="space-y-4">
      {SECTIONS.map((section) => {
        const Icon = section.icon;
        return (
          <div key={section.title} className="flex items-start gap-3">
            <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border border-border bg-muted/40">
              <Icon className="h-3.5 w-3.5 text-foreground/60" aria-hidden="true" />
            </span>
            <div className="min-w-0 flex-1">
              <p className="text-sm font-semibold text-foreground">{section.title}</p>
              <p className="mt-1 text-xs leading-relaxed text-foreground/65">{section.description}</p>
              {section.bullets ? (
                <ul className="mt-2 space-y-1">
                  {section.bullets.map((bullet) => (
                    <li key={bullet} className="flex gap-2 text-xs text-foreground/60">
                      <span className="mt-0.5 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-500" aria-hidden="true" />
                      {bullet}
                    </li>
                  ))}
                </ul>
              ) : null}
              {section.cta ? (
                <Link
                  href={section.cta.href}
                  className="mt-2.5 inline-flex items-center gap-1 text-xs font-medium text-blue-600 transition-colors hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
                >
                  {section.cta.label}
                  <ArrowRight className="h-3 w-3" aria-hidden="true" />
                </Link>
              ) : null}
            </div>
          </div>
        );
      })}
    </div>
  );
}
