-- Question Quality Tier 3 audit (v0.162.0 Phase D) — sampling queries, run read-only against production
-- 2026-09-27. Companion to docs/claude-plans/2026-09-27-question-quality-tier3-audit.md — that document's
-- appendix lists every item these queries returned; this file exists so the exact queries can be re-run
-- (the ORDER BY random() draw itself is NOT reproducible — a re-run will pull a different sample, which is
-- expected and fine for a spot-check, but means "0/65" cannot be re-verified against the identical rows,
-- only against a fresh draw of the same size and shape).
--
-- ⚠️ Two real bugs found and fixed during the audit, both worth stating plainly rather than smoothing over,
-- since this file is a CORRECTED reproduction of the queries, not a literal transcript of every query
-- actually executed:
--
-- 1. Query 1's first attempt selected `elem->>'answer'` as the keyed answer. Production stores the keyed
--    answer as `correctIndex` (an integer offset into `choices`), not the letter-based `answer` field the
--    prompt schema describes — the backend normalizes to an index at persistence time. That first attempt
--    returned NULL for every one of its 25 rows. IT WAS DISCARDED ENTIRELY AND NEVER JUDGED — none of its
--    rows appear anywhere in the audit document's appendix. Query 1 below is the RE-RUN, using
--    `correctIndex`, and it is what was actually read and judged (verified row-for-row against the appendix
--    table before this note was written).
-- 2. All three queries' `questionFormat` filter originally read `elem->>'questionFormat' IN ('MCQ', NULL)`
--    — in SQL, `IN (..., NULL)` never matches a NULL value (NULL compared to anything via IN is NULL, not
--    TRUE), so this silently dropped every question with a null `questionFormat` instead of including it.
--    Query 3 (exam pool) was written with the correct `(col IS NULL OR col = 'MCQ')` form from the start.
--    Queries 1 and 2 (below) have been corrected to match for this saved file, but **the versions actually
--    run for the audit's Sample 1 and Sample 2 still carried the `IN` bug** — both of those samples silently
--    under-covered null-`questionFormat` items. A live re-run to close this gap was not performed for this
--    document; if it matters, re-run queries 1 and 2 below (a fresh, non-reproducible draw) rather than
--    treating the numbers already in the audit doc as covering the null-format population.

-- Query 1: 25 questions, one per subject, from the 20 highest-volume subjects generated since 2026-09-20.
WITH recent_mcq AS (
  SELECT sp.id AS pack_id, sp.subject, sp.created_at, elem,
         row_number() OVER (PARTITION BY sp.subject ORDER BY random()) AS rn
  FROM study_packs sp, jsonb_array_elements(sp.quiz) elem
  WHERE sp.quiz IS NOT NULL
    AND (elem->>'questionFormat' IS NULL OR elem->>'questionFormat' = 'MCQ')
    AND sp.created_at >= '2026-09-20'
)
SELECT subject, elem->>'question' AS question, elem->'choices' AS choices,
       elem->'choices'->>((elem->>'correctIndex')::int) AS correct_choice, elem->>'explanation' AS explanation
FROM recent_mcq
WHERE rn = 1
ORDER BY random()
LIMIT 25;

-- Query 2: 20 assertion-style ("Statement 1: ... Statement 2: ... Which is correct?") questions since
-- 2026-09-15 — deliberately oversampled as the single highest-risk format for defensibility disputes.
WITH items AS (
  SELECT sp.id AS pack_id, sp.subject, elem
  FROM study_packs sp, jsonb_array_elements(sp.quiz) elem
  WHERE sp.quiz IS NOT NULL AND sp.created_at >= '2026-09-15'
    AND elem->>'question' LIKE 'Statement 1:%'
)
SELECT subject, elem->>'question' AS question, elem->'choices' AS choices,
       elem->'choices'->>((elem->>'correctIndex')::int) AS correct_choice, elem->>'explanation' AS explanation
FROM items
ORDER BY random()
LIMIT 20;

-- Query 3: 10 Board Exam + 10 Long Exam pool questions (READY pools only) — the harder, situational,
-- multi-step-reasoning prompt tier, and the store the one confirmed historical Tier 3 defect (the rotated-
-- square geometry question, incident doc line ~1075) was found in. Not covered by queries 1-2 at all.
WITH items AS (
  SELECT e.mode, e.study_pack_id, elem,
         row_number() OVER (PARTITION BY e.mode ORDER BY random()) AS rn
  FROM exam_question_pool e, jsonb_array_elements(e.questions) elem
  WHERE e.questions IS NOT NULL AND e.generation_status = 'READY'
    AND (elem->>'questionFormat' IS NULL OR elem->>'questionFormat' = 'MCQ')
)
SELECT mode, elem->>'question' AS question, elem->'choices' AS choices,
       elem->'choices'->>((elem->>'correctIndex')::int) AS correct_choice, elem->>'explanation' AS explanation
FROM items
WHERE rn <= 10
ORDER BY mode, rn;

-- NOT sampled, stated explicitly rather than silently omitted: challenge_quiz_question_bank and
-- generated_quizzes. Both are generated by the same core Quiz rules (the same "exactly one choice must be
-- correct" structural bar, the same H4/H5 explanation contract) as the two stores above, and the harder
-- Board/Long Exam prompt tier (query 3) is the more distinct risk surface already covered. Treat the audit's
-- conclusions as resting on 2 of 4 stores, not a full-corpus census -- Tier 3 has no deterministic predicate
-- to scan the other two cheaply the way Tier 1/2 checks could.
