ALTER TABLE users
    ADD COLUMN IF NOT EXISTS engagement_mode VARCHAR(32) NOT NULL DEFAULT 'FOCUSED',
    ADD COLUMN IF NOT EXISTS current_streak INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS longest_streak INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_study_date DATE;
