package com.studysnap.backend.entity;

public enum ActivityType {
    CREATED_STUDY_PACK,
    OPENED_STUDY_PACK,
    STARTED_QUICK_REVIEW,
    STARTED_ADAPTIVE_PRACTICE,
    COMPLETED_QUICK_REVIEW,
    COMPLETED_ADAPTIVE_QUIZ
}
