package com.studysnap.backend.entity;

public enum AnalyticsEventType {
    NOTE_CREATED,
    STUDY_PACK_GENERATED,
    QUICK_REVIEW_STARTED,
    CHALLENGE_QUIZ_STARTED,
    ADAPTIVE_PRACTICE_STARTED,
    PAYWALL_VIEWED,
    UPGRADE_CLICKED,
    SUBSCRIPTION_STARTED,
    PUBLIC_NOTE_VIEWED,
    PUBLIC_NOTE_COPIED,
    PUBLIC_NOTE_COPY_CLICKED,
    LOGIN,
    SIGNUP,
    LANDING_PAGE_VIEWED,
    LANDING_CTA_CLICKED,
    DEMO_OPENED,
    SIGNUP_STARTED,
    SIGNUP_COMPLETED,
    EMAIL_VERIFICATION_SENT,
    EMAIL_VERIFIED
}
