package com.studysnap.backend.entity;

public enum RetentionEmailType {
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    WELCOME,
    INACTIVITY,
    WEAK_CONCEPT,
    UNFINISHED_NOTE,
    WEEKLY_SUMMARY,
    DUE_CONCEPTS_DIGEST,
    KNOWLEDGE_IMPACT_DIGEST,
    SUBSCRIPTION_EXPIRY_7_DAY,
    SUBSCRIPTION_EXPIRY_1_DAY,
    SUBSCRIPTION_EXPIRED,
    RE_ENGAGEMENT_2025
}
