package com.studysnap.backend.service;

import com.studysnap.backend.dto.QuizDocxExportMode;
import com.studysnap.backend.dto.QuizItem;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

@Service
public class QuizDocxExportService {
    private static final String GENERATED_BY_LABEL = "Generated by NoteLib";
    private static final String DATE_GENERATED_PREFIX = "Date generated: ";
    private static final String ANSWER_KEY_HEADING = "Answer Key";
    private static final String EXPLANATIONS_HEADING = "Explanations";
    private static final String UNTITLED_NOTE = "untitled-note";
    private static final String QUIZ_FILENAME_SUFFIX = "-quiz.docx";
    private static final String QUIZ_WITH_ANSWERS_FILENAME_SUFFIX = "-quiz-with-answers.docx";
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("MMMM d, uuuu", Locale.US);

    public byte[] exportQuizToDocx(ExportableQuiz quiz, QuizDocxExportMode mode) {
        try (XWPFDocument document = new XWPFDocument();
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            addHeader(document, quiz);
            addQuestions(document, quiz.questions());
            if (mode == QuizDocxExportMode.WITH_ANSWERS) {
                addAnswerKey(document, quiz.questions());
                addExplanations(document, quiz.questions());
            }
            document.write(outputStream);
            return outputStream.toByteArray();
        } catch (IOException exception) {
            throw new IllegalStateException("Could not export quiz DOCX.", exception);
        }
    }

    public String buildFilename(String noteTitle, QuizDocxExportMode mode) {
        String baseName = sanitizeFilenameSegment(noteTitle);
        return baseName + (mode == QuizDocxExportMode.WITH_ANSWERS
                ? QUIZ_WITH_ANSWERS_FILENAME_SUFFIX
                : QUIZ_FILENAME_SUFFIX);
    }

    private void addHeader(XWPFDocument document, ExportableQuiz quiz) {
        XWPFParagraph titleParagraph = document.createParagraph();
        titleParagraph.setAlignment(ParagraphAlignment.LEFT);
        titleParagraph.setSpacingAfter(120);
        XWPFRun titleRun = titleParagraph.createRun();
        titleRun.setBold(true);
        titleRun.setFontSize(18);
        titleRun.setText(normalizeText(quiz.title()));

        if (quiz.subject() != null && !quiz.subject().isBlank()) {
            addBodyParagraph(document, quiz.subject(), true, 0);
        }
        addBodyParagraph(document, GENERATED_BY_LABEL, false, 0);
        addBodyParagraph(document, DATE_GENERATED_PREFIX + DATE_FORMATTER.format(quiz.generatedAt()), false, 240);
    }

    private void addQuestions(XWPFDocument document, List<QuizItem> questions) {
        for (int index = 0; index < questions.size(); index++) {
            QuizItem question = questions.get(index);
            XWPFParagraph questionParagraph = document.createParagraph();
            questionParagraph.setSpacingAfter(80);
            XWPFRun questionRun = questionParagraph.createRun();
            questionRun.setBold(true);
            questionRun.setFontSize(12);
            questionRun.setText((index + 1) + ". " + normalizeText(question.question()));

            List<String> choices = question.choices() == null ? List.of() : question.choices();
            for (int choiceIndex = 0; choiceIndex < choices.size(); choiceIndex++) {
                addBodyParagraph(document, answerLabel(choiceIndex) + ". " + normalizeText(choices.get(choiceIndex)), false, 0);
            }

            XWPFParagraph spacer = document.createParagraph();
            spacer.setSpacingAfter(220);
        }
    }

    private void addAnswerKey(XWPFDocument document, List<QuizItem> questions) {
        addSectionHeading(document, ANSWER_KEY_HEADING);
        for (int index = 0; index < questions.size(); index++) {
            QuizItem question = questions.get(index);
            Integer correctIndex = question.correctIndex();
            String answerLabel = correctIndex == null ? "-" : answerLabel(correctIndex);
            addBodyParagraph(document, (index + 1) + ". " + answerLabel, false, 0);
        }
    }

    private void addExplanations(XWPFDocument document, List<QuizItem> questions) {
        addSectionHeading(document, EXPLANATIONS_HEADING);
        for (int index = 0; index < questions.size(); index++) {
            QuizItem question = questions.get(index);
            addBodyParagraph(document, (index + 1) + ". " + normalizeText(question.explanation()), false, 120);
        }
    }

    private void addSectionHeading(XWPFDocument document, String text) {
        XWPFParagraph paragraph = document.createParagraph();
        paragraph.setSpacingBefore(120);
        paragraph.setSpacingAfter(80);
        XWPFRun run = paragraph.createRun();
        run.setBold(true);
        run.setFontSize(14);
        run.setText(text);
    }

    private void addBodyParagraph(XWPFDocument document, String text, boolean bold, int spacingAfter) {
        XWPFParagraph paragraph = document.createParagraph();
        paragraph.setSpacingAfter(spacingAfter);
        XWPFRun run = paragraph.createRun();
        run.setBold(bold);
        run.setFontSize(11);
        run.setText(normalizeText(text));
    }

    private String sanitizeFilenameSegment(String value) {
        if (value == null || value.isBlank()) {
            return UNTITLED_NOTE;
        }
        String normalized = value.trim()
                .toLowerCase(Locale.US)
                .replaceAll("[^a-z0-9]+", "-")
                .replaceAll("(^-+|-+$)", "");
        return normalized.isBlank() ? UNTITLED_NOTE : normalized;
    }

    private String normalizeText(String value) {
        return value == null || value.isBlank() ? "-" : value.trim();
    }

    private String answerLabel(int index) {
        return String.valueOf((char) ('A' + index));
    }

    public record ExportableQuiz(
            String title,
            String subject,
            OffsetDateTime generatedAt,
            List<QuizItem> questions
    ) {
        public ExportableQuiz {
            questions = questions == null ? List.of() : List.copyOf(questions);
        }
    }

    @Getter
    @RequiredArgsConstructor
    public static class QuizDocxFile {
        private final String filename;
        private final byte[] content;
    }
}
