import { TextEncoder } from "util";
import {
  buildMistakesOnlyExportFilename,
  buildQuizSessionExportFilename,
  buildWeakConceptsExportFilename,
  buildQuizSessionPdf,
  exportQuizSessionReviewDocument,
} from "@/lib/quiz-session-export";

if (!global.TextEncoder) {
  global.TextEncoder = TextEncoder as typeof global.TextEncoder;
}

const BASE_REVIEW = {
  sessionId: "session-1",
  studyPackId: "pack-1",
  sessionMode: "QUICK_REVIEW" as const,
  status: "COMPLETED" as const,
  totalQuestions: 2,
  correctAnswers: 1,
  scorePercentage: 50,
  retryCount: 0,
  durationSeconds: 180,
  weakConcepts: ["Photosynthesis"],
  conceptBreakdown: [
    {
      concept: "Photosynthesis",
      correctAnswers: 0,
      totalQuestions: 1,
      accuracyPercentage: 0,
    },
  ],
  quiz: [
    {
      question: "What is photosynthesis?",
      choices: ["Cell division", "Energy transfer", "Food production", "Protein synthesis"],
      correctIndex: 2,
      concept: "Photosynthesis",
      explanation: "Photosynthesis lets plants convert light energy into stored chemical energy.",
    },
    {
      question: "Which organelle is central to photosynthesis?",
      choices: ["Nucleus", "Chloroplast", "Ribosome", "Mitochondrion"],
      correctIndex: 1,
      concept: "Cell biology",
      explanation: "Chloroplasts contain chlorophyll and host the light-dependent reactions.",
    },
  ],
  selectedChoices: { 0: 1, 1: 1 },
  createdAt: "2026-04-11T10:00:00Z",
  completedAt: "2026-04-11T10:05:00Z",
};

describe("buildQuizSessionExportFilename", () => {
  it("builds a stable pdf filename for the exported quiz", () => {
    expect(buildQuizSessionExportFilename("Photosynthesis Notes", new Date("2026-04-14T08:00:00Z")))
      .toBe("notelib-quiz-photosynthesis-notes-2026-04-14.pdf");
  });
});

describe("buildMistakesOnlyExportFilename", () => {
  it("builds a stable mistakes-only pdf filename with the notelib-mistakes prefix", () => {
    expect(buildMistakesOnlyExportFilename("Photosynthesis Notes", new Date("2026-04-14T08:00:00Z")))
      .toBe("notelib-mistakes-photosynthesis-notes-2026-04-14.pdf");
  });
});

describe("buildQuizSessionPdf", () => {
  it("generates a pdf with summary, answers, and footer branding", () => {
    const pdfBytes = buildQuizSessionPdf({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      review: BASE_REVIEW,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    });

    const pdfText = Buffer.from(pdfBytes).toString("utf8");

    expect(pdfText.startsWith("%PDF-1.4")).toBe(true);
    expect(pdfText).toContain("Photosynthesis Notes");
    expect(pdfText).toContain("Quiz type: Quick Review");
    expect(pdfText).toContain("Score: 1/2");
    expect(pdfText).toContain("What is photosynthesis?");
    expect(pdfText).toContain("Your answer:");
    expect(pdfText).toContain("Incorrect");
    expect(pdfText).toContain("Correct answer:");
    expect(pdfText).toContain("Generated by NoteLib");
  });

  it("creates multiple pages for long quizzes without clipping everything onto one page", () => {
    const longReview = {
      ...BASE_REVIEW,
      totalQuestions: 14,
      quiz: Array.from({ length: 14 }, (_, index) => ({
        question: `Question ${index + 1} asks for a very detailed explanation about a long scientific process that should wrap cleanly across the exported PDF page without clipping.`,
        choices: [
          "First long answer choice for export layout testing",
          "Second long answer choice for export layout testing",
          "Third long answer choice for export layout testing",
          "Fourth long answer choice for export layout testing",
        ],
        correctIndex: 1,
        concept: `Concept ${index + 1}`,
        explanation: "This explanation is intentionally long to exercise multi-page wrapping in the generated PDF output.",
      })),
      selectedChoices: Object.fromEntries(Array.from({ length: 14 }, (_, index) => [String(index), 0])),
    };

    const pdfText = Buffer.from(buildQuizSessionPdf({
      noteTitle: "Long Quiz",
      noteSubject: "Biology",
      quizTypeLabel: "Challenge Quiz",
      review: longReview,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    })).toString("utf8");

    const pageMatches = pdfText.match(/\/Type \/Page\b/g) ?? [];
    expect(pageMatches.length).toBeGreaterThan(1);
  });
});

describe("buildQuizSessionPdf - mistakes-only", () => {
  it("includes only incorrect questions and the Mistakes Review section header", () => {
    const pdfText = Buffer.from(buildQuizSessionPdf({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      exportType: "mistakes-only",
      review: BASE_REVIEW,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    })).toString("utf8");

    expect(pdfText).toContain("Mistakes Review");
    expect(pdfText).toContain("Mistakes: 1/2 incorrect");
    // Q1 is incorrect (selected 1, correct 2) — must appear
    expect(pdfText).toContain("What is photosynthesis?");
    // Q2 is correct (selected 1, correct 1) — must not appear
    expect(pdfText).not.toContain("Which organelle is central to photosynthesis?");
    expect(pdfText).toContain("Your answer:");
    expect(pdfText).toContain("Correct answer:");
    expect(pdfText).toContain("Photosynthesis lets plants convert light energy");
    expect(pdfText).toContain("Generated by NoteLib");
  });

  it("shows the perfect score message when there are no mistakes", () => {
    const allCorrectReview = {
      ...BASE_REVIEW,
      // Both questions answered correctly
      selectedChoices: { 0: 2, 1: 1 },
    };

    const pdfText = Buffer.from(buildQuizSessionPdf({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      exportType: "mistakes-only",
      review: allCorrectReview,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    })).toString("utf8");

    expect(pdfText).toContain("Mistakes Review");
    expect(pdfText).toContain("Perfect Score");
    expect(pdfText).toContain("You answered all questions correctly.");
    expect(pdfText).not.toContain("What is photosynthesis?");
  });

  it("uses the mistakes-only filename when exportType is mistakes-only", async () => {
    const originalCreateObjectURL = URL.createObjectURL;
    const originalRevokeObjectURL = URL.revokeObjectURL;
    Object.defineProperty(URL, "createObjectURL", {
      configurable: true,
      writable: true,
      value: jest.fn().mockReturnValue("blob:mistakes-export"),
    });
    Object.defineProperty(URL, "revokeObjectURL", {
      configurable: true,
      writable: true,
      value: jest.fn(),
    });
    jest.spyOn(document.body, "appendChild");
    jest.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    jest.useFakeTimers();

    const result = await exportQuizSessionReviewDocument({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      exportType: "mistakes-only",
      review: BASE_REVIEW,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    });

    expect(result.filename).toBe("notelib-mistakes-photosynthesis-notes-2026-04-14.pdf");

    jest.runOnlyPendingTimers();
    jest.useRealTimers();
    jest.restoreAllMocks();
    Object.defineProperty(URL, "createObjectURL", { configurable: true, writable: true, value: originalCreateObjectURL });
    Object.defineProperty(URL, "revokeObjectURL", { configurable: true, writable: true, value: originalRevokeObjectURL });
  });
});

describe("buildWeakConceptsExportFilename", () => {
  it("builds a stable weak-concepts pdf filename with the notelib-weak-concepts prefix", () => {
    expect(buildWeakConceptsExportFilename("Photosynthesis Notes", new Date("2026-04-14T08:00:00Z")))
      .toBe("notelib-weak-concepts-photosynthesis-notes-2026-04-14.pdf");
  });
});

describe("buildQuizSessionPdf - weak-concepts", () => {
  it("includes only questions matching weak concepts and the Weak Concepts Review header", () => {
    const pdfText = Buffer.from(buildQuizSessionPdf({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      exportType: "weak-concepts",
      review: BASE_REVIEW,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    })).toString("utf8");

    expect(pdfText).toContain("Weak Concepts Review");
    // Q1 concept is "Photosynthesis" which is in weakConcepts — must appear
    expect(pdfText).toContain("What is photosynthesis?");
    // Q2 concept is "Cell biology" which is NOT in weakConcepts — must not appear
    expect(pdfText).not.toContain("Which organelle is central to photosynthesis?");
    expect(pdfText).toContain("Generated by NoteLib");
  });

  it("shows no weak concepts message when weakConcepts is empty", () => {
    const noWeakConceptsReview = {
      ...BASE_REVIEW,
      weakConcepts: [],
      selectedChoices: { 0: 2, 1: 1 },
    };

    const pdfText = Buffer.from(buildQuizSessionPdf({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      exportType: "weak-concepts",
      review: noWeakConceptsReview,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    })).toString("utf8");

    expect(pdfText).toContain("Weak Concepts Review");
    expect(pdfText).toContain("No weak concepts identified.");
    expect(pdfText).not.toContain("What is photosynthesis?");
  });

  it("uses the weak-concepts filename when exportType is weak-concepts", async () => {
    const originalCreateObjectURL = URL.createObjectURL;
    const originalRevokeObjectURL = URL.revokeObjectURL;
    Object.defineProperty(URL, "createObjectURL", { configurable: true, writable: true, value: jest.fn().mockReturnValue("blob:weak-concepts-export") });
    Object.defineProperty(URL, "revokeObjectURL", { configurable: true, writable: true, value: jest.fn() });
    jest.spyOn(document.body, "appendChild");
    jest.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    jest.useFakeTimers();

    const result = await exportQuizSessionReviewDocument({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      exportType: "weak-concepts",
      review: BASE_REVIEW,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    });

    expect(result.filename).toBe("notelib-weak-concepts-photosynthesis-notes-2026-04-14.pdf");

    jest.runOnlyPendingTimers();
    jest.useRealTimers();
    jest.restoreAllMocks();
    Object.defineProperty(URL, "createObjectURL", { configurable: true, writable: true, value: originalCreateObjectURL });
    Object.defineProperty(URL, "revokeObjectURL", { configurable: true, writable: true, value: originalRevokeObjectURL });
  });
});

describe("exportQuizSessionReviewDocument", () => {
  it("creates a downloadable pdf blob", async () => {
    const originalCreateObjectURL = URL.createObjectURL;
    const originalRevokeObjectURL = URL.revokeObjectURL;
    const createObjectUrlSpy = jest.fn().mockReturnValue("blob:quiz-export");
    const revokeObjectUrlSpy = jest.fn();
    Object.defineProperty(URL, "createObjectURL", {
      configurable: true,
      writable: true,
      value: createObjectUrlSpy,
    });
    Object.defineProperty(URL, "revokeObjectURL", {
      configurable: true,
      writable: true,
      value: revokeObjectUrlSpy,
    });
    const appendChildSpy = jest.spyOn(document.body, "appendChild");
    const clickSpy = jest.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(() => {});
    jest.useFakeTimers();

    const result = await exportQuizSessionReviewDocument({
      noteTitle: "Photosynthesis Notes",
      noteSubject: "Biology",
      quizTypeLabel: "Quick Review",
      review: BASE_REVIEW,
      exportedAt: new Date("2026-04-14T08:00:00Z"),
    });

    expect(result.filename).toBe("notelib-quiz-photosynthesis-notes-2026-04-14.pdf");
    expect(createObjectUrlSpy).toHaveBeenCalled();
    expect(appendChildSpy).toHaveBeenCalled();
    expect(clickSpy).toHaveBeenCalled();

    jest.runOnlyPendingTimers();
    expect(revokeObjectUrlSpy).toHaveBeenCalledWith("blob:quiz-export");

    clickSpy.mockRestore();
    appendChildSpy.mockRestore();
    Object.defineProperty(URL, "createObjectURL", {
      configurable: true,
      writable: true,
      value: originalCreateObjectURL,
    });
    Object.defineProperty(URL, "revokeObjectURL", {
      configurable: true,
      writable: true,
      value: originalRevokeObjectURL,
    });
    jest.useRealTimers();
  });
});
